image: java:8

pipelines:
  default:
    - step:
    caches:
    - gradle
    - android-sdk
         script:
            - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
            - unzip -o -qq android-sdk.zip -d android-sdk
            - export ANDROID_HOME="/opt/atlassian/pipelines/agent/build/android-sdk"
            - export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
            - yes | sdkmanager "platform-tools"
            - yes | sdkmanager "platforms;android-28"
            - yes | sdkmanager "build-tools;28.0.3"
            - yes | sdkmanager "extras;android;m2repository"
            - yes | sdkmanager "extras;google;m2repository"
            - yes | sdkmanager "extras;google;instantapps"
            - yes | sdkmanager --licenses
            - chmod a+x ./gradlew
            - chmod +x deploy-hockey.sh
            - ./gradlew assembleDebug
  definitions:
    caches:
    android-sdk: android-sdk