image: uber/android-build-environment:latest

pipelines:
  default:
    - step:
        script:
            - mkdir "${ANDROID_HOME}/licenses" || true
            - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
            - ./gradlew assembleDevDebug
            - . ./setup_export.sh
            ##########  UPLOAD APK TO SLACK #CHANNEL ##########
            # Setup the following enviroment variables on bitbucket pipelines  & 
            # SLACK_TOKEN - Obtain this token from: https://api.slack.com/custom-integrations/legacy-tokens
            # SLACK_CHANNEL - Channel name to upload the file. 
            - curl -F file=@"./app/build/outputs/apk/$FILE_NAME" -F channels=${SLACK_CHANNEL} -F token=${SLACK_TOKEN} https://slack.com/api/files.upload
            ##########  UPLOAD A CHANGELOG POST TO SLACK #CHANNEL ##########
            - curl -F content="---Uploaded by bitbucket pipelines, Pending manual edit---" -F filetype=post -F title="$FILE_TITLE CHANGELOG $BUILD_DATE" -F channels=${SLACK_CHANNEL} -F token=${SLACK_TOKEN} https://slack.com/api/files.upload
